# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=10000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
